# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech titbits
email: dave@davepacheco.com
description: > # this means to ignore newlines until "baseurl:"
  Random bits and bytes that make up tech titbits that I find interesting.
baseurl: "/tech" # the subpath of your site, e.g. /blog
url: "http://davepacheco.com" # the base hostname & protocol for your site
twitter_username: dapacheco
github_username:  dapacheco

# Build settings
markdown: kramdown
